package com.adamaho.goho.theme

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

@Immutable
data class GohoColors(
    val isDark: Boolean,
    val background: Color,
    val surface: Color, // cards
    val surfaceMuted: Color, // filter track, round icon buttons, thumbnail placeholder
    val surfaceMutedPressed: Color, // pressed round icon button
    val segmentSelected: Color, // selected filter segment
    val surfacePressed: Color, // pressed row
    val skeletonBase: Color,
    val skeletonShimmer: Color,
    val photoWellCenter: Color, // photo frame and viewer stay dark in both themes
    val photoWellEdge: Color,
    val photoControl: Color, // expand/close buttons that sit on the photo well
    val textPrimary: Color,
    val textSecondary: Color,
    val textTertiary: Color,
    val divider: Color,
    val outline: Color, // thumbnail border, light-mode card ring
    val shadow: Color, // ambient/spot color for neutral shadows
    val accent: Color,
    val accentRing: Color,
    val accentPressed: Color,
    val onAccent: Color,
    val buttonSecondary: Color,
    val buttonSecondaryPressed: Color,
    val accentShadow: Color, // spot color under the Scan button
    val accentContainer: Color,
    val onAccentContainer: Color,
    val accentShimmer: Color,
    val danger: Color,
    val dangerRing: Color,
    val dangerPressed: Color,
    val onDanger: Color,
    val dangerShadow: Color,
    val dangerContainer: Color,
    val onDangerContainer: Color,
    val sheet: Color,
    val grabber: Color,
    val scrim: Color,
    val attention: Color,
    val attentionContainer: Color,
    val buttonInnerRing: Color,
    val dangerInnerRing: Color,
    val secondaryRing: Color,
    val buttonShadowAlpha: Float,
    val buttonWideShadowAlpha: Float,
    val secondaryShadowAlpha: Float,
    val secondaryWideShadowAlpha: Float,
    val statusCard: Color,
    val statusCardRing: Color,
)

private val PhotoWellCenter = Color(0xFF2A2833)
private val PhotoWellEdge = Color(0xFF0C0B10)
private val PhotoControl = Color(0xFF1F1E2A).copy(alpha = 0.78f)

val GohoDarkColors =
    GohoColors(
        isDark = true,
        danger = Color(0xFFCF4440),
        dangerRing = Color(0xFFA9302D),
        dangerPressed = Color(0xFFBA3A36),
        onDanger = Color(0xFFFFFFFF),
        dangerShadow = Color.Black,
        dangerContainer = Color(0xFF4B1E20),
        onDangerContainer = Color(0xFFF7908A),
        sheet = Color(0xFF22212E),
        grabber = Color(0xFF42404F),
        scrim = Color.Black.copy(alpha = 0.55f),
        background = Color(0xFF15141D),
        surface = Color(0xFF1F1E2A),
        surfaceMuted = Color(0xFF1F1E2A),
        surfaceMutedPressed = Color(0xFF2B2A38),
        segmentSelected = Color(0xFF2B2A38),
        surfacePressed = Color(0xFF252432),
        skeletonBase = Color(0xFF2B2A38),
        skeletonShimmer = Color(0xFF3A3948),
        photoWellCenter = PhotoWellCenter,
        photoWellEdge = PhotoWellEdge,
        photoControl = PhotoControl,
        textPrimary = Color(0xFFF1EFF8),
        textSecondary = Color(0xFFBBB8CC),
        textTertiary = Color(0xFF9794AB),
        divider = Color.White.copy(alpha = 0.05f),
        outline = Color.White.copy(alpha = 0.06f),
        shadow = Color.Black,
        accent = Color(0xFFA6ABF0),
        accentRing = Color(0xFF8288D2),
        accentPressed = Color(0xFF959AE3),
        onAccent = Color(0xFF17183D),
        buttonSecondary = Color(0xFF2B2A38),
        buttonSecondaryPressed = Color(0xFF252432),
        accentShadow = Color.Black,
        accentContainer = Color(0xFF2A2C50),
        onAccentContainer = Color(0xFFB7BBF6),
        accentShimmer = Color(0xFFE4E5FD),
        attention = Color(0xFFF2A07C),
        attentionContainer = Color(0xFF43271C),
        buttonInnerRing = Color.White.copy(alpha = 0.22f),
        dangerInnerRing = Color.White.copy(alpha = 0.16f),
        secondaryRing = Color.White.copy(alpha = 0.08f),
        buttonShadowAlpha = 0.4f,
        buttonWideShadowAlpha = 0.6f,
        secondaryShadowAlpha = 0.4f,
        secondaryWideShadowAlpha = 0.6f,
        statusCard = Color.White.copy(alpha = 0.025f),
        statusCardRing = Color.White.copy(alpha = 0.07f),
    )

val GohoLightColors =
    GohoColors(
        isDark = false,
        danger = Color(0xFFD2443F),
        dangerRing = Color(0xFFB33532),
        dangerPressed = Color(0xFFBE3A36),
        onDanger = Color(0xFFFFFFFF),
        dangerShadow = Color(0xFF7A1F1C),
        dangerContainer = Color(0xFFFFE9E7),
        onDangerContainer = Color(0xFFB42A26),
        sheet = Color(0xFFFFFFFF),
        grabber = Color(0xFFDAD6E0),
        scrim = Color(0xFF26233A).copy(alpha = 0.34f),
        background = Color(0xFFFBF8F4),
        surface = Color(0xFFFFFFFF),
        surfaceMuted = Color(0xFFF1EEF4),
        surfaceMutedPressed = Color(0xFFE6E2EC),
        segmentSelected = Color(0xFFFFFFFF),
        surfacePressed = Color(0xFFF7F4F9),
        skeletonBase = Color(0xFFECE9F1),
        skeletonShimmer = Color(0xFFFBF8F4),
        photoWellCenter = PhotoWellCenter,
        photoWellEdge = PhotoWellEdge,
        photoControl = PhotoControl,
        textPrimary = Color(0xFF26233A),
        textSecondary = Color(0xFF5B5870),
        textTertiary = Color(0xFF6E6A83),
        divider = Color(0xFF26233A).copy(alpha = 0.06f),
        outline = Color(0xFF26233A).copy(alpha = 0.08f),
        shadow = Color(0xFF26233A),
        accent = Color(0xFF8B91D6),
        accentRing = Color(0xFF767CC2),
        accentPressed = Color(0xFF7D83CB),
        onAccent = Color(0xFF1B1C45),
        buttonSecondary = Color(0xFFFFFFFF),
        buttonSecondaryPressed = Color(0xFFF7F4F9),
        accentShadow = Color(0xFF3A3D86),
        accentContainer = Color(0xFFE9E9FB),
        onAccentContainer = Color(0xFF444AA0),
        accentShimmer = Color(0xFF9CA1E6),
        attention = Color(0xFFA6472A),
        attentionContainer = Color(0xFFFFE8DD),
        buttonInnerRing = Color.White.copy(alpha = 0.22f),
        dangerInnerRing = Color.White.copy(alpha = 0.14f),
        secondaryRing = Color(0xFF26233A).copy(alpha = 0.06f),
        buttonShadowAlpha = 0.16f,
        buttonWideShadowAlpha = 0.32f,
        secondaryShadowAlpha = 0.05f,
        secondaryWideShadowAlpha = 0.18f,
        statusCard = Color.White.copy(alpha = 0.6f),
        statusCardRing = Color(0xFF26233A).copy(alpha = 0.06f),
    )
