package com.adamaho.goho.theme

import androidx.compose.ui.unit.dp

object GohoSpacing {
    val buttonHeight = 52.dp
    val buttonHorizontal = 20.dp
    val buttonGap = 10.dp
    val buttonIcon = 18.dp
    val buttonIconGap = 8.dp
    val buttonElevation = 2.dp
    val flatElevation = 0.dp
    val previewMinHeight = 480.dp
    val photoPadding = 24.dp
    val photoElevation = 8.dp
    val photoCloseIcon = 20.dp
    val photoCloseTop = 4.dp
    val photoDismissDistance = 120.dp
    val photoDragRange = 300.dp
    val previewFooterTop = 16.dp
    val screenMargin = 16.dp
    val textInset = 20.dp
    val textInsetFromMargin = 4.dp // textInset - screenMargin
    val cardPadding = 16.dp
    val cardVerticalPadding = 4.dp
    val rowVertical = 12.dp
    val rowMinHeight = 72.dp
    val thumbWidth = 40.dp
    val thumbHeight = 48.dp
    val thumbToText = 12.dp
    val dividerStart = 68.dp // cardPadding + thumbWidth + thumbToText
    val detailTopBarHeight = 56.dp
    val detailBackIcon = 20.dp
    val detailHeroGap = 8.dp
    val detailPhotoTop = 20.dp
    val detailPhotoHeight = 200.dp
    val detailRowVertical = 12.dp
    val detailBottom = 24.dp
    val itemVertical = 14.dp
    val itemGap = 16.dp
    val itemCardTop = 2.dp
    val detailRowHeight = 47.dp
    val sectionTop = 24.dp
    val sectionLabelBottom = 8.dp
    val fabBottom = 28.dp
    val hairline = 1.dp
    val headerHeight = 44.dp
    val headerTop = 4.dp
    val headerFadeHeight = 12.dp
    val lineGap = 5.dp
    val contentGap = 12.dp
    val pillHeight = 22.dp
    val pillHorizontal = 9.dp
    val skeletonWidth = 52.dp
    val skeletonHeight = 12.dp
    val listBottom = 112.dp
    val fabHeight = 56.dp
    val fabStart = 18.dp
    val fabEnd = 22.dp
    val fabIcon = 22.dp
    val fabIconGap = 9.dp
    val fabElevation = 3.dp
    val pressedElevation = 0.5.dp
    val iconStroke = 2.dp
    val compactWidth = 360.dp
    val filterTop = 16.dp
    val filterPadding = 3.dp
    val filterGap = 6.dp
    val filterTouchInset = 4.dp
    val filterVisualHeight = 36.dp
    val placeholderWidth = 20.dp
    val placeholderHeight = 28.dp
    val placeholderStroke = 1.5.dp
    val segmentHorizontal = 10.dp
    val segmentCountGap = 5.dp
    val badgeSize = 20.dp
    val amountMaxWidth = 148.dp
}
